version: "2"

services:
  centrifugo:
    image: centrifugo/centrifugo
    #mem_limit: 200m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./centrifugo:/centrifugo
    ports:
      - 8010:8000  
